import Link from "next/link";
import { ArrowUpRight, Check, CircleDot, Code2, FileText, Layers3, MessageSquare, Milestone, Play, Sparkles } from "lucide-react";

const features = [
  { icon: FileText, title: "Brief analysis", text: "Turn a loose client note into goals, pages, risks, and the questions that unblock the first call." },
  { icon: Layers3, title: "Scope builder", text: "Shape deliverables, included work, exclusions, and revision rounds before expectations drift." },
  { icon: Milestone, title: "Milestone planning", text: "Give the work a sensible sequence so every review has a clear reason and next step." },
  { icon: MessageSquare, title: "Approvals & changes", text: "Share an immutable scope snapshot, collect feedback, and lock approved work in place." },
];

export default function Home() {
  return <>
    <section className="landing-hero"><header className="site-header"><Link className="brand" href="/"><span className="brand-mark">✳</span> Nexora</Link><nav className="nav"><a href="#product">Product</a><a href="#workflow">How it works</a><a href="#faq">FAQ</a><Link className="nav-cta" href="/workspace">Open workspace <ArrowUpRight size={13} style={{ verticalAlign: "-2px" }} /></Link></nav></header><div className="hero-grid"><div className="hero-copy"><div className="eyebrow">A calmer way to scope digital work</div><h1>Clear scope.<br />Smoother projects<span>.</span></h1><p>Nexora turns an unstructured web brief into a practical plan your client can understand, review, and approve.</p><div className="hero-actions"><Link className="button-primary" href="/workspace/new">Create a project <ArrowUpRight size={13} style={{ verticalAlign: "-2px" }} /></Link><a className="play-link" href="#workflow"><span><Play size={10} fill="currentColor" /></span> See the workflow</a></div><div className="hero-stats"><div className="hero-stat"><strong>01</strong><small>brief to scope</small></div><div className="hero-stat"><strong>04</strong><small>scope building blocks</small></div><div className="hero-stat"><strong>01</strong><small>approval snapshot</small></div></div></div><div className="hero-orbit" aria-hidden="true"><div className="orbit-core" /></div></div></section>
    <div className="trust-row"><span>MADE FOR INDEPENDENT TEAMS</span><span>Designer-led</span><span>Developer-ready</span><span>Client-readable</span><span>Local by default</span></div>
    <section className="landing-section section-split" id="product"><div><div className="section-kicker">01 — The problem</div><h2 className="section-title">A more capable first conversation.</h2><p className="section-copy">The strongest projects start before the first screen is designed. Nexora gives the brief somewhere useful to go: into a shared scope that makes decisions, trade-offs, and ownership visible.</p><Link className="button-secondary" href="/workspace/new">Start with a brief <ArrowUpRight size={13} style={{ verticalAlign: "-2px" }} /></Link></div><div className="about-art" aria-label="Abstract red light across a dark surface" /></section>
    <section className="landing-section" id="features"><div className="feature-head"><div><div className="section-kicker">02 — What you get</div><h2 className="section-title">Everything you need to make the work legible.</h2></div><p className="section-copy">A small, focused workspace for the part of a project where clarity pays off most.</p></div><div className="feature-grid">{features.map(({ icon: Icon, title, text }) => <article className="feature-card" key={title}><Icon className="feature-icon" size={19} /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="landing-section" id="workflow"><div className="workflow-grid"><div><div className="section-kicker">03 — How it works</div><h2 className="section-title">From raw notes to a confident yes.</h2></div><div className="step-list"><div className="step"><div className="step-num">01</div><h3>Capture the brief</h3><p>Paste the words as they arrived. Keep the messy context.</p></div><div className="step"><div className="step-num">02</div><h3>Build the scope</h3><p>Edit the useful structure: pages, work, timing, and limits.</p></div><div className="step"><div className="step-num">03</div><h3>Share & approve</h3><p>Send a review link. Feedback stays visible and approval locks the snapshot.</p></div></div></div></section>
    <section className="landing-section" id="faq"><div className="faq-layout"><div><div className="section-kicker">04 — FAQ</div><h2 className="section-title">A few useful answers.</h2></div><div className="faq-list"><details className="faq-item"><summary>Is Nexora an AI product?</summary><p>The built-in analyzer is a transparent local tool that works immediately. An optional AI analysis mode can help when you choose to configure it.</p></details><details className="faq-item"><summary>Can a client change an approved scope?</summary><p>Approval locks the snapshot. A later note can be recorded as a change request without silently rewriting what was approved.</p></details><details className="faq-item"><summary>Where is project data stored?</summary><p>Projects are saved on this computer. Review links work while your local Nexora app is running.</p></details><details className="faq-item"><summary>Can I export a scope?</summary><p>Yes. Project editors offer a Markdown export, and review pages include a print view so a browser can save the scope as a PDF.</p></details></div></div></section>
    <section className="landing-section landing-cta"><div><div className="section-kicker">Ready to get started?</div><h2 className="section-title">Turn your next brief<br />into something clear.</h2><Link className="button-primary" href="/workspace/new">Create a project <ArrowUpRight size={13} style={{ verticalAlign: "-2px" }} /></Link></div><div aria-hidden="true" className="orbit-core" /></section>
    <footer><div className="site-footer"><div><Link className="brand" href="/"><span className="brand-mark">✳</span> Nexora</Link><p className="footer-note">A local workspace for better freelance web projects.</p></div><div className="footer-col"><h4>Product</h4><a href="#product">Brief analysis</a><a href="#features">Scope builder</a><a href="#workflow">Approvals</a></div><div className="footer-col"><h4>Workspace</h4><Link href="/workspace">Overview</Link><Link href="/workspace/new">New project</Link></div><div className="footer-col"><h4>About</h4><a href="#faq">FAQ</a><a href="#product">Principles</a></div></div><div className="copyright"><span>© 2026 Nexora. Local by design.</span><span>Built for focused project conversations</span></div></footer>
  </>;
}
