"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { AdminCustomerDetail as Customer } from "@/lib/types";

export function AdminCustomerDetail({ id }: { id: string }) {
  const [customer, setCustomer] = useState<Customer | null>(null);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/admin/customers/${id}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not load customer."); setCustomer(data.customer); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load customer.")); }, [id]);
  async function setSuspended(suspended: boolean) {
    if (!customer || !window.confirm(`${suspended ? "Suspend" : "Reactivate"} ${customer.email}?`)) return;
    setBusy(true); setError(""); setMessage("");
    try { const response = await fetch(`/api/admin/customers/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ suspended, reason: suspended ? "Admin action" : "Access restored" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not update access."); setCustomer({ ...customer, suspended }); setMessage(suspended ? "Account suspended." : "Account reactivated."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update access."); } finally { setBusy(false); }
  }
  if (error && !customer) return <div className="workspace-main"><p className="form-error" role="alert">{error}</p><Link className="button-secondary" href="/admin">Back to admin</Link></div>;
  if (!customer) return <div className="workspace-main"><p className="muted-copy">Loading customer detail…</p></div>;
  return <div className="workspace-main"><Link className="back-link" href="/admin">← Back to admin</Link><div className="workspace-heading"><div><div className="section-kicker">Admin / customer detail</div><h1>{customer.profile?.fullName || customer.email}</h1><p>{customer.email} · Joined {new Date(customer.joinedAt).toLocaleDateString()}</p></div><span className={`status ${customer.suspended ? "status-changes_requested" : "status-approved"}`}>{customer.suspended ? "Suspended" : "Active"}</span></div><div className="admin-detail-grid"><section className="overview-card"><div className="section-kicker">Access</div><h2>Account safeguards</h2><p className="profile-muted">This page exposes suspension only; role and account-permission changes are managed in the server allowlist. Suspension requires a fresh administrator TOTP verification at AAL2.</p><button className={customer.suspended ? "button-primary" : "button-danger"} disabled={busy} onClick={() => void setSuspended(!customer.suspended)} type="button">{customer.suspended ? "Reactivate account" : "Suspend account"}</button>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}</section><section className="overview-card"><div className="section-kicker">Profile</div><h2>{customer.profile?.company || "No company"}</h2><p>{customer.profile?.roleTitle || "No role title"}</p><p className="profile-muted">{customer.profile?.bio || "No profile bio."}</p><dl className="detail-list"><div><dt>Email verified</dt><dd>{customer.emailConfirmedAt ? new Date(customer.emailConfirmedAt).toLocaleDateString() : "No"}</dd></div><div><dt>Last sign in</dt><dd>{customer.lastSignInAt ? new Date(customer.lastSignInAt).toLocaleString() : "—"}</dd></div></dl></section></div><section className="overview-card"><div className="section-kicker">Projects</div><h2>Customer projects</h2>{customer.projects.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Project</th><th>Status</th><th>Updated</th></tr></thead><tbody>{customer.projects.map((project) => <tr key={project.id}><td><strong><Link className="text-link" href={`/admin/projects/${project.id}`}>{project.title}</Link></strong><span>{project.id}</span></td><td><span className={`status status-${project.status}`}>{project.status.replaceAll("_", " ")}</span></td><td>{new Date(project.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></div> : <p className="empty-history">No projects found.</p>}</section></div>;
}
