"use client";

import Link from "next/link";
import { ArrowUpRight, Search } from "lucide-react";
import { useMemo, useState } from "react";
import type { Project } from "@/lib/types";

const labels: Record<Project["status"], string> = { draft: "Draft", shared: "Shared", changes_requested: "Changes requested", approved: "Approved" };

export function WorkspaceHome({ projects }: { projects: Project[] }) {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all");
  const visible = useMemo(() => projects.filter((project) => `${project.title} ${project.client}`.toLowerCase().includes(search.toLowerCase()) && (status === "all" || project.status === status)), [projects, search, status]);
  return <div className="workspace-main"><div className="workspace-heading"><div><div className="section-kicker">Workspace / overview</div><h1>Your projects</h1><p>Make the next decision easier to see.</p></div><Link className="button-primary" href="/workspace/new">New brief <ArrowUpRight size={13} style={{ verticalAlign: "-2px" }} /></Link></div><div style={{ display: "flex", gap: 10, marginBottom: 23 }}><div style={{ position: "relative", flex: 1, maxWidth: 300 }}><Search size={14} style={{ color: "#777", left: 12, position: "absolute", top: 12 }} /><input aria-label="Search projects" className="search-bar" onChange={(event) => setSearch(event.target.value)} placeholder="Search projects" style={{ paddingLeft: 34, width: "100%" }} value={search} /></div><select aria-label="Filter projects" className="search-bar" onChange={(event) => setStatus(event.target.value)} value={status}><option value="all">All statuses</option><option value="draft">Drafts</option><option value="shared">Shared</option><option value="changes_requested">Changes requested</option><option value="approved">Approved</option></select></div>{visible.length ? <div className="project-grid">{visible.map((project) => <Link className="project-card" href={`/workspace/projects/${project.id}`} key={project.id}><div className="project-card-top"><div><span className="mono-label">{project.status === "draft" ? "Active project" : "Review state"}</span><h2>{project.title}</h2><span className="project-client">{project.client}</span></div><ArrowUpRight size={16} color="#8c8989" /></div><p style={{ color: "#858181", fontSize: 11, marginTop: 22 }}>{project.analysis.summary}</p><div className="project-card-footer"><span className={`status status-${project.status}`}>{labels[project.status]}</span><span style={{ color: "#686464", fontSize: 10 }}>{new Date(project.updatedAt).toLocaleDateString()}</span></div></Link>)}</div> : <div className="empty-state"><div className="section-kicker">No matching projects</div><p>{projects.length ? "Try a different search or status." : "Start with a client brief and Nexora will help you shape the first useful scope."}</p>{!projects.length && <Link className="button-primary" href="/workspace/new">Create your first project</Link>}</div>}</div>;
}
